### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Bigrah2** [wagerr/WagerrWalletAndroid#1]
Hi,

On my Galaxy Tab 5 the app crashes when i click the big red "wallet" Button that has the coininfo in it every second time. i can reproduce it. first time it opens the new window and the second time the app closes.

**Comment by wagerrdeveloper** [comment]
Hi. Thanks for the feedback. This should now be resolved in the latest version
https://github.com/wagerr/WagerrWalletAndroid/releases/tag/244
