### ISSUE TITLE
Wrong title on BET payout

### ISSUE THREAD

**Issue by TheLunchb0x** [wagerr/WagerrWalletAndroid#3]
I bet on the Nationals last night and won. The payout came through with event 0 and the title of Liverpool instead of the actual event. I did receive the correct payout it's just labeled wrong. Looks like it may be defaulting to zero.
![Screenshot_20191030-072314_Wagerr Bet](https://user-images.githubusercontent.com/43994451/67854029-fec09700-fae5-11e9-8c28-a55e443f53b4.jpg)

**Comment by zeroedge83** [comment]
issue addressed
